version: '3'

services:
  third-party:
    image: lee920024/thrifty-third-party
    restart: always
    networks:
      - thrifty_network

  backend:
    image: lee920024/thrifty-backend
    restart: always
    networks:
      - thrifty_network

  frontend-admin:
    image: lee920024/thrifty-frontend-admin
    restart: always
    ports:
      - "3000:3000"
    networks:
      - thrifty_network

  frontend-user:
    image: lee920024/thrifty-frontend-user
    # build: ./frontend_user
    restart: always
    networks:
      - thrifty_network
      
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf:/etc/nginx/ssl/:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - thrifty_network

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./certbot/logs:/var/log/letsencrypt
    command: certonly --webroot -w /var/www/certbot --force-renewal --email lee920024@gmail.com -d thrifty-tw.shop --agree-tos

networks:
  thrifty_network:
    driver: bridge
 